on:
  push:
    branches:
      - feat/github-automatisation

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TEST_MYSQL_HOST: localhost
      TEST_MYSQL_USER: test_user
      TEST_MYSQL_PASSWORD: test_password
      TEST_MYSQL_DATABASE: test_database

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_password
          MYSQL_DATABASE: test_database
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Install dependencies
        run: npm install
 # hello
      - name: Run tests 
        run: |
          cd api_hello_world
          npm test
